### PR TITLE
Update PageTypes.php

### PR DESCRIPTION
**Pull request by newerton**
Add INSTAGRAM_STREAM.
https://developers.facebook.com/docs/marketing-api/validation/v2.5#placement

### CODE REVIEW

**Comment by newerton** [comment]
In the documentation I did not find the type **legacyexternal** and **logout**.
It will be removed? If so, change the file.

Sorry my English.

**Comment by duliomatos** [comment]
Thx for the contribution, @newerton! Merged.

**Comment by newerton** [comment]
Update file!

**Comment by duliomatos** [comment]
Your patch is on branch legacy, and version 2.6.0 of the SDK!

**Comment by newerton** [comment]
https://developers.facebook.com/docs/marketing-api/validation/v2.6#placement
Objective: CONVERSIONS
Placement: desktopfeed, rightcolumn, **instagramstream**, mobilefeed, mobileexternal

**Comment by duliomatos** [comment]
hmmm some regression, I'll update it again ;-)

**Comment by newerton** [comment]
Thanks Dulio!

**Comment by duliomatos** [comment]
Check branch `legacy` which is the current stable version: https://github.com/facebook/facebook-php-ads-sdk/blob/legacy/src/FacebookAds/Object/Values/PageTypes.php
Thx for noticing, I'll fix master.

**Pull request merged**
