### PR TITLE
explain that account_id should begin with "act_"

### PR DESCRIPTION
**Pull request by cornernote**
squishes commits as requested in #37

### CODE REVIEW

**Comment by pruno** [comment]
Hi @cornernote,

our coding style doesn't allow more than 80 chars per-line. can you please shrink it or move the comment on top of the declaration.

Thanks for your contributions!

**Comment by cornernote** [comment]
Hey @pruno,

I just want to add a simple comment so that other people don't have the same issue I had.  To do this I have submitted several pull requests, unfortunately none of which satisfy the coding standards.

I think it will be easier if one of the team members can apply this change for me.

**Comment by pruno** [comment]
Hi @cornernote,

I'll add a comment as you suggested.
I wish this process could have been smoother and i can understand your feeling.
We do value contributions and we care about contributors acknowledgement, i recognize this can sometimes collide with the need of maintain a strict codling style. We'll take focus in finding a way to smooth this process.

Again, thanks for contributing.

**Comment by pruno** [comment]
closed by https://github.com/facebook/facebook-php-ads-sdk/commit/953d0dc4327ab457a9212d27d3b24c68a196d577

**Pull request closed without merging**
