### PR TITLE
Adding RESERVED buying type & VIDEO_VIEWS objective

### PR DESCRIPTION
**Pull request by minhsepteni**

### CODE REVIEW

**Comment by minhsepteni** [comment]
Hi,
I've registered as a contributor at  https://code.facebook.com/cla. Could
you please review my pull request again
https://github.com/facebook/facebook-php-ads-sdk/pull/57 ?
Thank you!

On Wed, Jan 7, 2015 at 6:38 AM, Facebook Community Bot <
notifications@github.com> wrote:

> Thank you for your pull request and welcome to our community. We require
> contributors to sign our Contributor License Agreement, and we don't seem
> to have you on file. In order for us to review and merge your code, please
> sign up at https://code.facebook.com/cla - and if you have received this
> in error or have any questions, please drop us a line at cla@fb.com.
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/facebook-php-ads-sdk/pull/57#issuecomment-68955011>
> .
>



-- 
Lê Tuấn Minh

**Comment by pruno** [comment]
Hi @minhsepteni 

can you please remove this commit from the PR?
https://github.com/minhsepteni/facebook-php-ads-sdk/commit/10bd1645b8c21aff6cae040958b4ae5524d72a39
This fix is already in our repo.

thanks for your contribution!

**Comment by pruno** [comment]
@minhsepteni,

no worries, i've manually imported it: https://github.com/facebook/facebook-php-ads-sdk/commit/3dc3e6645114ea3c47f92284cb2cf953ed162d9a.

on the other end your fork seems to have become a bit messy. Since your changes are all in our master now, probably the faster and simpler thing that you can do is re-fork from scratch.

**Comment by minhsepteni** [comment]
Thank you!

**Pull request closed without merging**
