### PR TITLE
Cursor loses appsecret_proof after creating request from url

### PR DESCRIPTION
**Pull request by AloneCoder**

### CODE REVIEW

**Comment by pruno** [comment]
@AloneCoder Thanks for opening this.

How about using

~~~php
$request_params->enhance($query);
~~~

to avoid make this specific to the appsecret_proof?

**Comment by AloneCoder** [comment]
Looks pretty, thank you!
Sorry for my proposal of a problem-specific hack, that was my first experience of working with sdk's sources

**Comment by pruno** [comment]
No worries, thank you for contributing!

Just a quick last thing: can you please squash everything in 1 commit?

**Comment by AloneCoder** [comment]
I finally squashed commits, but it seems that something went wrong 😟

**Comment by pruno** [comment]
that's perfect, Scrutinizer has incurred in some downtimes early today.

Thanks!

**Pull request merged**
