### PR TITLE
Fix typo in readme

### PR DESCRIPTION
**Pull request by yamsellem**
Method `getCampaigns` does not exists. The sample seems to refer to method `getAdCampaigns`.

### CODE REVIEW

**Comment by pruno** [comment]
@yamsellem 

Thanks for sending this. We do require contributors to sign our CLA before accepting.
Closing due to inactivity, feel free to reopen if you agree to sign the CLA.

**Comment by yamsellem** [comment]
@pruno I've already signed (and this is just a typo fix ^_^)

**Comment by pruno** [comment]
@yamsellem 

we don't have a record of your CLA signature (did you signed with this account?).
Unfortunately i can't accept the PR without, even if it's for just a typo :(

**Comment by yamsellem** [comment]
@pruno yep, I've sign with this account. If I try to sign again, I get a `The 'Email' value has been registered on this form before. If you would like to update an existing contributor account, please email cla@fb.com with your details.`

You should find it somewhere ;-).

**Comment by pruno** [comment]
Thanks @yamsellem

**Pull request merged**
