### PR TITLE
Fix some phpDoc-blocks 

### PR DESCRIPTION
**Pull request by AloneCoder**

### CODE REVIEW

**Comment by pruno** [comment]
thanks for the PR @AloneCoder,

assureIsValidValue looks good but createOptimalVersion doesn't throw, can you explain your change?

**Comment by AloneCoder** [comment]
It may be thrown in Curl/Curl55 __construct function and unhandled via createOptimalVersion call

**Comment by pruno** [comment]
the condition for throwing will never take place as createOptimalVersion is using the same logic to chose which version to use, ergo createOptimalVersion will never throw. the checks in the curl classes are there in the case someone should try to instantiate directly

**Comment by pruno** [comment]
Thanks @AloneCoder, 

apologies for the delay: if you can squash everything in 1 commit i'll merge this

**Pull request closed without merging**
