### PR TITLE
add is_autobid to AdsetFields

### PR DESCRIPTION
**Pull request by minhsepteni**

### CODE REVIEW

**Comment by paulbain** [comment]
thanks for the pull request, unfortunately this is not a publicly documented field so we cannot accept this pull request right now.

**Comment by paulbain** [comment]
also I think you deleted the gitignore file

**Comment by pruno** [comment]
Hey @minhsepteni,

we can accept this, but i cannot merge as is. Would you mind resend a PR with a single commit?

Thanks

**Comment by minhsepteni** [comment]
Hey @pruno 
here you are https://github.com/minhsepteni/facebook-php-ads-sdk/commit/a96d48670a6bca939ce40d07e7ccdba746f2c873

**Pull request closed without merging**
